### ISSUE TITLE
When I try to compile this, the error occured!

### ISSUE THREAD

**Issue by Willis814** [CodevDynamics/Codev-autopilot#11]
╰─ make px4_fmu-v5_default                                                   ─╯
[0/475] Performing build step for 'px4io_firmware'
ninja: no work to do.
[22/474] Building CXX object src/modul...dules__commander.dir/Commander.cpp.obj
FAILED: src/modules/commander/CMakeFiles/modules__commander.dir/Commander.cpp.obj 
/usr/bin/arm-none-eabi-g++  -DCONFIG_ARCH_BOARD_PX4_FMU_V5 -DMODULE_NAME=\"commander\" -DPX4_MAIN=commander_app_main -D_SYS_CDEFS_H_ -D_SYS_REENT_H_ -D__CUSTOM_FILE_IO__ -D__PX4_NUTTX -D__STDC_FORMAT_MACROS -I../../boards/px4/fmu-v5/src -I../../platforms/nuttx/src/px4/common/include -I. -Isrc/lib -I../../platforms/nuttx/src/px4/stm/stm32f7/include -I../../platforms/common -I../../platforms/common/include -I../../src -I../../src/include -I../../src/lib -I../../src/lib/matrix -I../../src/modules -INuttX/nuttx/arch/arm/src/armv7-m -INuttX/nuttx/arch/arm/src/chip -INuttX/nuttx/arch/arm/src/common -INuttX/apps/include -Iexternal/Install/include -I../../src/lib/ecl -I../../src/modules/commander/Arming/PreFlightCheck -I../../src/modules/commander/Arming/ArmAuthorization -I../../src/modules/commander/Arming/HealthFlags -isystem ../../platforms/nuttx/NuttX/include/cxx -isystem NuttX/nuttx/include/cxx -isystem NuttX/nuttx/include -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard -Os -DNDEBUG   -g -fdata-sections -ffunction-sections -fomit-frame-pointer -fmerge-all-constants -fno-signed-zeros -fno-trapping-math -freciprocal-math -fno-math-errno -fno-strict-aliasing -fvisibility=hidden -include visibility.h -Wall -Wextra -Werror -Warray-bounds -Wcast-align -Wdisabled-optimization -Wdouble-promotion -Wfatal-errors -Wfloat-equal -Wformat-security -Winit-self -Wlogical-op -Wpointer-arith -Wshadow -Wuninitialized -Wunknown-pragmas -Wunused-variable -Wno-missing-field-initializers -Wno-missing-include-dirs -Wno-unused-parameter -fdiagnostics-color=always -fno-builtin-printf -fno-strength-reduce -Wformat=1 -Wunused-but-set-variable -Wno-format-truncation -fcheck-new -fno-exceptions -fno-rtti -fno-threadsafe-statics -Wreorder -Wno-overloaded-virtual -nostdinc++ -fno-sized-deallocation -Wframe-larger-than=2048 -std=gnu++14 -MD -MT src/modules/commander/CMakeFiles/modules__commander.dir/Commander.cpp.obj -MF src/modules/commander/CMakeFiles/modules__commander.dir/Commander.cpp.obj.d -o src/modules/commander/CMakeFiles/modules__commander.dir/Commander.cpp.obj -c ../../src/modules/commander/Commander.cpp
../../src/modules/commander/Commander.cpp: In member function 'virtual void Commander::run()':
../../src/modules/commander/Commander.cpp:1810:4: error: 'board_shutdown' was not declared in this scope
 1810 |    board_shutdown();
      |    ^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
[39/474] Building CXX object src/modul...keFiles/modules__ekf2.dir/EKF2.cpp.obj
ninja: build stopped: subcommand failed.
make: *** [Makefile:226：px4_fmu-v5_default] error 1

the error occured in the source code of the following:
if (power_state_notification(PWR_BUTTON_REQUEST_SHUT_DOWN) == PWR_BUTTON_RESPONSE_SHUT_DOWN_NOW) {
				up_mdelay(200);
				board_shutdown();
			}
			
I looked up the source code and there is only code for int type: int board_shutdown(void);
How should I resolved this problem?

**Comment by Abner0907** [comment]
> power_state_notification(PWR_BUTTON_REQUEST_SHUT_DOWN) == PWR_BUTTON_RESPONSE_SHUT_DOWN_NOW)

The errors comes from the above issue,  the power button. you need to add it by yourself. As this branch is suit for codev_dp1000-v2_default

**Comment by Willis814** [comment]
I tried to make it in another computer ,it also failed,and below is the error:
mass@mass-NUC8i7BEH:~/Codev-autopilot$ make px4_fmu-v5_default
[0/425] Performing build step for 'px4io_firmware'
ninja: no work to do.
[8/422] Building CXX object src/module...dules__commander.dir/Commander.cpp.obj
FAILED: src/modules/commander/CMakeFiles/modules__commander.dir/Commander.cpp.obj 
/opt/gcc-arm-none-eabi-9-2020-q2-update/bin/arm-none-eabi-g++  -DCONFIG_ARCH_BOARD_PX4_FMU_V5 -DMODULE_NAME=\"commander\" -DPX4_MAIN=commander_app_main -D_SYS_CDEFS_H_ -D_SYS_REENT_H_ -D__CUSTOM_FILE_IO__ -D__PX4_NUTTX -D__STDC_FORMAT_MACROS -I../../boards/px4/fmu-v5/src -I../../platforms/nuttx/src/px4/common/include -I. -Isrc/lib -I../../platforms/nuttx/src/px4/stm/stm32f7/include -I../../platforms/common -I../../platforms/common/include -I../../src -I../../src/include -I../../src/lib -I../../src/lib/matrix -I../../src/modules -INuttX/nuttx/arch/arm/src/armv7-m -INuttX/nuttx/arch/arm/src/chip -INuttX/nuttx/arch/arm/src/common -INuttX/apps/include -Iexternal/Install/include -I../../src/lib/ecl -I../../src/modules/commander/Arming/PreFlightCheck -I../../src/modules/commander/Arming/ArmAuthorization -I../../src/modules/commander/Arming/HealthFlags -isystem ../../platforms/nuttx/NuttX/include/cxx -isystem NuttX/nuttx/include/cxx -isystem NuttX/nuttx/include -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard -Os -DNDEBUG   -g -fdata-sections -ffunction-sections -fomit-frame-pointer -fmerge-all-constants -fno-signed-zeros -fno-trapping-math -freciprocal-math -fno-math-errno -fno-strict-aliasing -fvisibility=hidden -include visibility.h -Wall -Wextra -Werror -Warray-bounds -Wcast-align -Wdisabled-optimization -Wdouble-promotion -Wfatal-errors -Wfloat-equal -Wformat-security -Winit-self -Wlogical-op -Wpointer-arith -Wshadow -Wuninitialized -Wunknown-pragmas -Wunused-variable -Wno-missing-field-initializers -Wno-missing-include-dirs -Wno-unused-parameter -fdiagnostics-color=always -Wno-stringop-truncation -fno-builtin-printf -fno-strength-reduce -Wformat=1 -Wunused-but-set-variable -Wno-format-truncation -fcheck-new -fno-exceptions -fno-rtti -fno-threadsafe-statics -Wreorder -Wno-overloaded-virtual -nostdinc++ -fno-sized-deallocation -Wframe-larger-than=2048 -std=gnu++14 -MD -MT src/modules/commander/CMakeFiles/modules__commander.dir/Commander.cpp.obj -MF src/modules/commander/CMakeFiles/modules__commander.dir/Commander.cpp.obj.d -o src/modules/commander/CMakeFiles/modules__commander.dir/Commander.cpp.obj -c ../../src/modules/commander/Commander.cpp
../../src/modules/commander/Commander.cpp: In member function 'virtual void Commander::run()':
../../src/modules/commander/Commander.cpp:1810:4: error: 'board_shutdown' was not declared in this scope
 1810 |    board_shutdown();
      |    ^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
[17/422] Building CXX object src/modul...1.dir/FixedwingPositionControl.cpp.obj
ninja: build stopped: subcommand failed.
make: *** [Makefile:226: px4_fmu-v5_default] Error 1


The same is the definition of this function. At the same time, I don’t understand your answer. I’m sorry for that.

**Comment by Abner0907** [comment]
it is no bussiness about the computer, it is the code which do not define the 'PWR_BUTTON_REQUEST_SHUT_DOWN' which cause your issue. you can not use this branch to build  px4_fmu-v5_default, it do not support it.

**Comment by Willis814** [comment]
OK, I'll try it. Thank you for your reply!
